version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: morningvalue-postgres
    environment:
      POSTGRES_DB: morningvalue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - morningvalue-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: morningvalue-backend
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      DATABASE_URL: jdbc:postgresql://postgres:5432/morningvalue
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - morningvalue-network
    restart: unless-stopped

  # React Frontend (Development with hot-reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: morningvalue-frontend
    environment:
      # Backend URL accessible from browser (host machine)
      REACT_APP_API_BASE_URL: http://localhost:8080
      # Enable hot reload
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot-reload
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      # Prevent node_modules from being overwritten
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - morningvalue-network
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local

networks:
  morningvalue-network:
    driver: bridge
